### ISSUE TITLE
%s not available in script commands?

### ISSUE THREAD

**Issue by PMK** [mikaelbr/mversion#18]
I'm using mversion in my projects and I like it! My website projects I want to have the version in the index.html file as a meta-tag. Using precommit and postcommit scripts I thought I could use `sed` to search and replace a special string.

``` json
{
    "scripts": {
        "precommit": "sed -e s/\{mversion\}/%s/g app/index.html",
        "postcommit": "git push --tags && sed -e s/%s/\{mversion\}/g app/index.html"
    }
}
```

``` html
<meta name="version" content="{mversion}" />
```

The problem I have is that `%s` is not available in the scripts, or I don't know how to use it. Could you implement this or update the documentation?
If I move the commands to its own file, maybe you can append the `%s` as an argument of the shell script.

**Comment by adambiggs** [comment]
@mikaelbr is it possible to add this to the `precommit` hook as well? I want to generate a changelog, but I need to let the changelog generator know what the *next* version is.
