### ISSUE TITLE
mversion patch @0.0.5 produces 0.1.0 instead of 0.0.6

### ISSUE THREAD

**Issue by bcherny** [mikaelbr/mversion#23]
Explicitly setting the new version doesn't help.

```sh
$ mversion -m 0.0.6
Updated to new version: v0.1.0
Updated package.json
Updated bower.json
Commited to git and created tag v0.1.0
```

**Comment by mikaelbr** [comment]
Very good answer and good support, @christophwitzko . Thanks for helping out!

@bcherny I'm closing this as it doesn't seem to be a issue.
