### ISSUE TITLE
Undo changes when pre-commit hook fails

### ISSUE THREAD

**Issue by blakeembrey** [mikaelbr/mversion#24]
Just an idea, but I started using `pre-commit` and now when it fails when running `mversion -m` I'd expect it the changes to rollback. In fact, if anything in the process fails I feel like it should undo the changes.

**Comment by mikaelbr** [comment]
Hi and thanks for the feedback! I think this is a good idea. As far as I can think of now, it shouldn't be too difficult. Just need the following, for support on post-commit as well:

1. Have the previous version in a variable, re-set version in files.
2. Check if comitted with message as defined as message (if so, `git reset`)
3. Check if tag created witht the tag name as defined (if so, `git tag -d`)

Scripts defined in pre-/post-hooks can't be undone, though.

**Comment by mikaelbr** [comment]
I read your issue again and saw that I read it incorrectly the first time. `pre-commit` only needed a git checkout, I implemented support for this in 53a55e3. Would be great if you could test it out and give feedback (can try it out by doing `npm link` and `npm link mversion`).

**Comment by blakeembrey** [comment]
@mikaelbr It doesn't look like it works because I want to rollback the `package.json` bump. However, since it's already staged it can't just be checked back out.

**Comment by mikaelbr** [comment]
Pre-commit should happen before staging of the package.json, and thus a git checkout should work? It seemed to work as expected with me. Testing with just "exit 1".

**Comment by blakeembrey** [comment]
Hmm, the files are all staged for me (why would it do a commit without it being staged?). I even tried it with just `exit 1`.

**Comment by blakeembrey** [comment]
I need to do a `git reset HEAD package.json` to revert the state.

**Comment by mikaelbr** [comment]
What version are you testing out?

From code:
Precommit happens here: https://github.com/mikaelbr/mversion/blob/master/index.js#L183-L188
But staging doesn't happen before: https://github.com/mikaelbr/mversion/blob/master/index.js#L192

Are you sure you are using the current un-released version?

(You can try the "edge" version by doing `npm install -g mikaelbr/mversion`)

**Comment by blakeembrey** [comment]
@mikaelbr I'm already using the latest version. Here's the issue:

**Make `package.json` and `git init`:**

```
{
  "version": "0.0.0",
  "scripts": {
    "test": "exit 1"
  },
  "dependencies": {
    "pre-commit": "^1.0.6"
  }
}
```

**Attempt to version:**

```
mversion patch -m
```

Note that `package.json` is staged.

**Comment by mikaelbr** [comment]
I did this in a clean directory:

With package.json:

```json
{
  "version": "0.0.0",
  "scripts": {
    "test": "exit 1"
  },
  "dependencies": {
    "pre-commit": "^1.0.6"
  }
}
```

And `.mversionrc`:
```json
{
  "scripts": {
    "precommit": "npm test"
  }
}
```

```shell
➜  mversion  npm i -g mikaelbr/mversion

➜  mversion  nano package.json

➜  mversion  git init
Initialized empty Git repository in /tmp/mversion/.git/

➜  mversion git:(master) ✗ gst
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	package.json

nothing added to commit but untracked files present (use "git add" to track)

➜  mversion git:(master) ✗ ga . && gc -m "Initial commit"
[master (root-commit) 4c28c45] Initial commit
 1 file changed, 9 insertions(+)
 create mode 100644 package.json

➜  mversion git:(master) nano .mversionrc

➜  mversion git:(master) ✗ ga . && gc -m "Adds mversion rc"
[master 4d4f471] Adds mversion rc
 1 file changed, 5 insertions(+)
 create mode 100644 .mversionrc

➜  mversion git:(master) mversion patch -m
Error running precommit: Command failed: /bin/sh -c npm test
npm ERR! Test failed.  See above for more details.

Stopping execution
➜  mversion git:(master) gst
On branch master
nothing to commit, working directory clean
```

As you see, there is no changes in the repo and the minor release has been reverted.

**Comment by blakeembrey** [comment]
@mikaelbr Why would I need the `.mversionrc` file? The `pre-commit` module should already be adding the precommit hook to git for me. That looks like the different between what we're going and why it doesn't work as expected for me - I expected the change to work with existing git commit hooks.

**Comment by mikaelbr** [comment]
Ag, no, sorry. This module doesn't work on git pre-commit hooks but as seperate hooks much like the npm "post_install" hook. See the section with mversionrc in the readme for more info

**Comment by blakeembrey** [comment]
Ah, ok. Thanks for the heads up. Do you expect it to be possible to hook onto normal `pre-commit` hooks since I have tests that run every time I try to commit (which may fail). Either way, it's a neat little piece of functionality - I just figured it'd be easy enough to rollback everything automatically with a `git reset HEAD .` and `git checkout -- .` since (IIRC) you only version when the working directory is clean.

**Comment by mikaelbr** [comment]
I think the way it is now is the cleanest/easiest way to interact with it. Feel free to add a patch, though, but until then I'm closing this. Thanks for your feedback.
