### ISSUE TITLE
Paramenter `-m` doesn't create a tag

### ISSUE THREAD

**Issue by pablodenadai** [mikaelbr/mversion#25]
Hi there, thanks for creating `mversion`. :-)

The parameter `-m` does create a commit but it doesn't "release" a tag.

Not sure if I'm missing something or maybe I misunderstood what you meant by "tag".

**Comment by mikaelbr** [comment]
Hm. That's weird. I use it regularly, and actually did a `mversion minor -m` just now, and created this tag: https://github.com/mikaelbr/node-notifier/releases/tag/v4.1.0

After doing `mversion minor -m` try writing `git tag` and see if it is listed there.

One thing to remember is that tags need to be pushed explicitly on Github. So if you see something listed by doing `git tag` you can push the tags by doing `git push --tags`.

**Comment by pablodenadai** [comment]
Good to know that it should create a tag.

I managed to push it manually using `$ git push --tags`.

```
$ git tag

v0.6.0
v0.6.1
v0.6.2
```

```
`$ git push --tags`

Counting objects: 1, done.
Writing objects: 100% (1/1), 162 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/financial-calcs/loan-calculator-engine.git
 * [new tag]         v0.6.2 -> v0.6.2
```

**Comment by mikaelbr** [comment]
Very good. So I take it as everything works as expected?
Thanks for your issue and your feedback!

**Comment by pablodenadai** [comment]
Thanks mate, I'll add a hook in the `.mversionrc` to push it.

Cheers!
