### ISSUE TITLE
no precommit nor postcommit execution

### ISSUE THREAD

**Issue by Offirmo** [mikaelbr/mversion#33]
Here is my .mversionrc :
```json
{
	"scripts": {
		"preupdate": "echo preupdate",
		"precommit": "echo precommit",
		"postcommit": "echo postcommit",
		"postupdate": "echo postupdate"
	}
}
```
Then `mversion patch` :
```
Output running preupdate: preupdate

Updated to new version: v0.0.6
Updated package.json
Updated bower.json
Output running postupdate: postupdate
```
no trace of commit hooks execution... (mversion v1.10.1)

**Comment by Offirmo** [comment]
BTW when running `mversion --version`, the `preupdate` hook is executed.

**Comment by mikaelbr** [comment]
Thanks for your issue! Are you running mversion with the "-m" property? Without it no commit will be made.

**Comment by Offirmo** [comment]
oh oh subtile... no -m for me (testing hook scripts)

**Comment by Offirmo** [comment]
Thanks for the help.
